### ISSUE TITLE
VDateTimeSelect Properties

### ISSUE THREAD

**Issue by Mashiane** [kolesnikovav/vuetify-toolkit#14]
Hi

I have noted that on the pen provided for the VDateTimeSelect there are properties like:

**chips, multiple, autocomplete and items**

Q1. how are these relevant to the date time select component? 
Q2. can one select multiple date & times from this component? If so, how?

**Comment by kolesnikovav** [comment]
Hi
This component is needed to be remade.
this proprerties - maybe remove or hide from component.
It's better to use calendar when You need multiple date.
