### ISSUE TITLE
Module not found: Error: Can't resolve 'sass-loader'

### ISSUE THREAD

**Issue by nekooee** [kolesnikovav/vuetify-toolkit#28]
I try to install this component. after install I run watch but get an error" Module not found: Error: Can't resolve 'sass-loader' "
after I install sass-loader but get the same error again.
I use webpack.
my webpack.mix.js:
```
mix.js('resources/js/admin.js', 'public/js')
    .js('resources/js/app.js', 'public/js')
    .js('resources/js/front.js', 'public/js').vue()
    .postCss('resources/css/admin.css', 'public/css')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('@tailwindcss/jit'),
        require('autoprefixer')
    ])
    .webpackConfig(require('./webpack.config'));

if (mix.inProduction()) {
    mix.version();
}

```

**Comment by kolesnikovav** [comment]
Hi. 
Can Your give me a link for reproduce?

**Comment by nekooee** [comment]
> Hi.
> Can Your give me a link for reproduce?

Hi,
sorry I do not understand what you mean. What should I link to you from?

**Comment by kolesnikovav** [comment]
I need your project in which you encountered a problem. Or how can I create it and get the same error.

**Comment by nekooee** [comment]
> I need your project in which you encountered a problem. Or how can I create it and get the same error.

my project is laravel + Vuejs(only admin panel), I don't think there will be an online run and debug. I'm trying to make the same error in a link for you.

**Comment by nekooee** [comment]
> I need your project in which you encountered a problem. Or how can I create it and get the same error.

my problem solved :
https://laravel-mix.com/docs/4.0/upgrade#vue-component-sass-preprocessing

from the laravel mix document I found that I should run:
`npm install sass sass-loader `
