### ISSUE TITLE
autocomplete only search in parents?

### ISSUE THREAD

**Issue by nekooee** [kolesnikovav/vuetify-toolkit#29]
Hi,
I try to search in list width autocomplete options. but it only works for parents. 
This option In tree mode loses its efficiency.  Is there no solution to it?

before type:
![image](https://user-images.githubusercontent.com/6003803/111704761-e7a65480-8854-11eb-8f8c-7e6bd2f42033.png)

after type:
![image](https://user-images.githubusercontent.com/6003803/111704820-fd1b7e80-8854-11eb-8aa8-50e3719df3a2.png)

**Comment by kolesnikovav** [comment]
Hi @nekooee . 
I'm so sorry for late answer...
I have prepare new version of library with correct search in treeselect.
Currently, node, that containing matching items, does not open by default, but filter works well.
I will works about open filtered nodes later.

**Comment by nlien** [comment]
Hi! Thanks for this extension! Exactly what I was looking for. Any progress on the opening of the filtered nodes?
