### ISSUE TITLE
Please provide a javascript version for <script></script>use. Thanks

### ISSUE THREAD

**Issue by Mashiane** [kolesnikovav/vuetify-toolkit#8]
Hi there

I'm using vuetify via CDN and using it locally. Can you please be kind and also avail a bundled javascript option for your components so that I can include it via the <script></script> tag in my web app?

Thanks and you are doing a wonderful job here. Keep it up.

**Comment by kolesnikovav** [comment]
@Mashiane Hi. Sorry for late answer and thank your for positive feedback!
I have thinking about cdn usage and I will try to implement it as it possible.
